name: Build Node.js project
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_API_TOKEN }}
          service: ${{ secrets.RAILWAY_SERVICE_ID }}
          
  frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
        
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
        
      - name: Deploy to Netlify
        run: npx netlify deploy --prod --dir=frontend/dist --site=$NETLIFY_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
