name: Deploy Application
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy Backend & Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Déploiement Backend sur Railway
      - name: Install Railway CLI
        run: npm i -g @railway/cli
      
      - name: Deploy Backend to Railway
        run: railway up
        working-directory: backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
      
      # Déploiement Frontend sur Netlify
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
      
      - name: Install Frontend dependencies
        working-directory: ./frontend
        run: npm install
      
      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build
      
      - name: Deploy to Netlify
        run: npx netlify deploy --prod --dir=frontend/dist --site=$NETLIFY_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
